# Site-wide settings
title: "Your awesome site title"
author:
  name: "Your Name"
  email: "your-email@example.com"
description: >
  Write an awesome description for your site. This appears in search and feeds.

# Build settings
theme: minima   # Use the gem version of Minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima-specific settings
minima:
  skin: auto    # Enables adaptive light/dark mode

# Optional: show excerpts on homepage (default: false)
# minima:
#   show_excerpts: true

# Optional: Format for post dates
# minima:
#   date_format: "%b %d, %Y"

# Optional: Social links
minima:
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/Eagle57f"
